import React, { useState } from 'react';
import { Card, Input, Button, Tabs, Space, Typography, Row, Col, Select, message, Checkbox } from 'antd';
import { Globe, Copy, Download, RefreshCw, FileCode, Check, Search, Shield } from 'lucide-react';
import { motion } from 'framer-motion';
import ToolContent from '../../components/ToolContent';

const { Title, Text, Paragraph } = Typography;
const { TextArea } = Input;
const { Option } = Select;

const SeoSuite = ({ defaultTab = 'sitemap' }) => {
  const [activeTab, setActiveTab] = useState(defaultTab);
  const [inputText, setInputText] = useState('');
  const [outputText, setOutputText] = useState('');

  // Sitemap Generator state
  const [siteUrl, setSiteUrl] = useState('');
  const [changeFreq, setChangeFreq] = useState('daily');
  const [priority, setPriority] = useState('0.8');
  const [includeDate, setIncludeDate] = useState(true);

  // Robots.txt Generator state
  const [userAgent, setUserAgent] = useState('*');
  const [crawlDelay, setCrawlDelay] = useState('none');
  const [sitemapPath, setSitemapPath] = useState('');
  const [disallowedPaths, setDisallowedPaths] = useState('/admin/\n/cgi-bin/');

  const handleCopy = (text) => {
    if (!text) return message.warning('No output content to copy');
    navigator.clipboard.writeText(text);
    message.success('Copied to clipboard! 📋');
  };

  const handleDownload = (text, filename) => {
    if (!text) return message.warning('No content to download');
    const blob = new Blob([text], { type: 'text/plain;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = filename;
    link.click();
    URL.revokeObjectURL(url);
    message.success(`${filename} downloaded! 💾`);
  };

  // Sitemap Generator logic
  const generateSitemap = () => {
    if (!siteUrl.trim()) return message.warning('Please enter your website URL');
    let url = siteUrl.trim();
    if (!url.startsWith('http://') && !url.startsWith('https://')) {
      url = 'https://' + url;
    }

    const today = new Date().toISOString().split('T')[0];
    const xml = `<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
  <!-- Primary Domain -->
  <url>
    <loc>${url}/</loc>
    ${includeDate ? `<lastmod>${today}</lastmod>` : ''}
    <changefreq>${changeFreq}</changefreq>
    <priority>1.0</priority>
  </url>
  <!-- Main Pages -->
  <url>
    <loc>${url}/about</loc>
    ${includeDate ? `<lastmod>${today}</lastmod>` : ''}
    <changefreq>${changeFreq}</changefreq>
    <priority>${priority}</priority>
  </url>
  <url>
    <loc>${url}/contact</loc>
    ${includeDate ? `<lastmod>${today}</lastmod>` : ''}
    <changefreq>${changeFreq}</changefreq>
    <priority>${priority}</priority>
  </url>
  <url>
    <loc>${url}/tools</loc>
    ${includeDate ? `<lastmod>${today}</lastmod>` : ''}
    <changefreq>${changeFreq}</changefreq>
    <priority>${priority}</priority>
  </url>
</urlset>`;

    setOutputText(xml);
    message.success('XML Sitemap generated! 🗺️');
  };

  // Robots.txt Generator logic
  const generateRobotsTxt = () => {
    let robots = `# Robots.txt generated by AllSarkari Tools\n`;
    robots += `User-agent: ${userAgent}\n`;
    
    if (crawlDelay !== 'none') {
      robots += `Crawl-delay: ${crawlDelay}\n`;
    }

    const paths = disallowedPaths.split('\n').filter(p => p.trim());
    paths.forEach(p => {
      robots += `Disallow: ${p.trim()}\n`;
    });

    robots += `Allow: /\n`;

    if (sitemapPath.trim()) {
      let smUrl = sitemapPath.trim();
      if (!smUrl.startsWith('http://') && !smUrl.startsWith('https://')) {
        smUrl = 'https://' + smUrl;
      }
      robots += `\nSitemap: ${smUrl}`;
    }

    setOutputText(robots);
    message.success('Robots.txt generated! 🤖');
  };

  return (
    <div className="max-w-7xl mx-auto py-24 px-4 min-h-screen">
      <div className="text-center mb-16">
        <div className="inline-flex items-center gap-2 bg-white/5 border border-white/10 px-4 py-2 rounded-full mb-6 backdrop-blur-md">
          <Globe size={16} className="text-primary animate-pulse" />
          <span className="text-xs font-bold text-gray-300 uppercase tracking-widest">SEO Tools Suite • 100% Client-Side</span>
        </div>
        <h1 className="responsive-title !text-white !mb-4 tracking-tighter uppercase">SEO Tools Suite</h1>
        <Paragraph className="!text-gray-400 text-lg sm:text-xl">
          Generate XML sitemaps, customize robots.txt instructions, and prepare SEO tags for search visibility.
        </Paragraph>
      </div>

      <Tabs
        activeKey={activeTab}
        onChange={(key) => { setActiveTab(key); setOutputText(''); }}
        className="custom-tabs-glass mb-16"
        items={[
          {
            key: 'sitemap',
            label: <span className="flex items-center gap-2 text-white font-bold"><FileCode size={16} /> Sitemap Generator</span>,
            children: (
              <Card className="glass-card !p-8">
                <Row gutter={[32, 32]}>
                  <Col xs={24} md={12}>
                    <Space direction="vertical" className="w-full" size="large">
                      <div>
                        <Text className="text-gray-400 font-bold block mb-2 uppercase text-[10px] tracking-widest">Website URL</Text>
                        <Input 
                          placeholder="e.g. example.com" 
                          value={siteUrl} 
                          onChange={e => setSiteUrl(e.target.value)} 
                          className="!bg-white/5 !border-white/10 !text-white !rounded-xl !h-12"
                        />
                      </div>

                      <Row gutter={16}>
                        <Col span={12}>
                          <Text className="text-gray-400 font-bold block mb-2 uppercase text-[10px] tracking-widest">Change Frequency</Text>
                          <Select value={changeFreq} onChange={setChangeFreq} className="w-full !bg-[#0c0721] !border-white/10 !text-white custom-select-glow">
                            <Option value="always">Always</Option>
                            <Option value="hourly">Hourly</Option>
                            <Option value="daily">Daily</Option>
                            <Option value="weekly">Weekly</Option>
                            <Option value="monthly">Monthly</Option>
                          </Select>
                        </Col>
                        <Col span={12}>
                          <Text className="text-gray-400 font-bold block mb-2 uppercase text-[10px] tracking-widest">Default Priority</Text>
                          <Select value={priority} onChange={setPriority} className="w-full !bg-[#0c0721] !border-white/10 !text-white custom-select-glow">
                            <Option value="1.0">1.0 (Highest)</Option>
                            <Option value="0.8">0.8 (High)</Option>
                            <Option value="0.5">0.5 (Normal)</Option>
                            <Option value="0.3">0.3 (Low)</Option>
                          </Select>
                        </Col>
                      </Row>

                      <div>
                        <Checkbox checked={includeDate} onChange={e => setIncludeDate(e.target.checked)} className="!text-gray-400 font-bold">
                          Include Current Date (lastmod tag)
                        </Checkbox>
                      </div>

                      <Button type="primary" size="large" onClick={generateSitemap} className="neon-button !w-full !h-14">
                        Generate XML Sitemap
                      </Button>
                    </Space>
                  </Col>

                  <Col xs={24} md={12}>
                    <div className="flex justify-between items-center mb-2">
                      <Text className="text-gray-400 font-bold uppercase text-[10px] tracking-widest">Generated XML</Text>
                      <div className="flex gap-2">
                        <Button size="small" icon={<Copy size={12} />} onClick={() => handleCopy(outputText)} className="!bg-white/5 !border-white/10 !text-white">Copy</Button>
                        <Button size="small" icon={<Download size={12} />} onClick={() => handleDownload(outputText, 'sitemap.xml')} className="!bg-white/5 !border-white/10 !text-white">Download</Button>
                      </div>
                    </div>
                    <TextArea 
                      rows={12}
                      value={outputText}
                      readOnly
                      placeholder="Your sitemap.xml content will appear here..."
                      className="!bg-white/[0.01] !border-white/10 !text-green-400 !rounded-xl font-mono text-xs"
                    />
                  </Col>
                </Row>
              </Card>
            )
          },
          {
            key: 'robots',
            label: <span className="flex items-center gap-2 text-white font-bold"><Search size={16} /> Robots.txt Generator</span>,
            children: (
              <Card className="glass-card !p-8">
                <Row gutter={[32, 32]}>
                  <Col xs={24} md={12}>
                    <Space direction="vertical" className="w-full" size="large">
                      <Row gutter={16}>
                        <Col span={12}>
                          <Text className="text-gray-400 font-bold block mb-2 uppercase text-[10px] tracking-widest">User Agent</Text>
                          <Select value={userAgent} onChange={setUserAgent} className="w-full !bg-[#0c0721] !border-white/10 !text-white custom-select-glow">
                            <Option value="*">* (All Search Bots)</Option>
                            <Option value="Googlebot">Googlebot Only</Option>
                            <Option value="Bingbot">Bingbot Only</Option>
                          </Select>
                        </Col>
                        <Col span={12}>
                          <Text className="text-gray-400 font-bold block mb-2 uppercase text-[10px] tracking-widest">Crawl Delay (Seconds)</Text>
                          <Select value={crawlDelay} onChange={setCrawlDelay} className="w-full !bg-[#0c0721] !border-white/10 !text-white custom-select-glow">
                            <Option value="none">No Delay</Option>
                            <Option value="5">5 Seconds</Option>
                            <Option value="10">10 Seconds</Option>
                          </Select>
                        </Col>
                      </Row>

                      <div>
                        <Text className="text-gray-400 font-bold block mb-2 uppercase text-[10px] tracking-widest">Disallowed Paths (one per line)</Text>
                        <TextArea 
                          rows={3} 
                          value={disallowedPaths} 
                          onChange={e => setDisallowedPaths(e.target.value)} 
                          className="!bg-white/5 !border-white/10 !text-white !rounded-xl"
                        />
                      </div>

                      <div>
                        <Text className="text-gray-400 font-bold block mb-2 uppercase text-[10px] tracking-widest">Sitemap Path URL (Optional)</Text>
                        <Input 
                          placeholder="e.g. example.com/sitemap.xml" 
                          value={sitemapPath} 
                          onChange={e => setSitemapPath(e.target.value)} 
                          className="!bg-white/5 !border-white/10 !text-white !rounded-xl !h-12"
                        />
                      </div>

                      <Button type="primary" size="large" onClick={generateRobotsTxt} className="neon-button !w-full !h-14">
                        Generate Robots.txt
                      </Button>
                    </Space>
                  </Col>

                  <Col xs={24} md={12}>
                    <div className="flex justify-between items-center mb-2">
                      <Text className="text-gray-400 font-bold uppercase text-[10px] tracking-widest">Generated Robots.txt</Text>
                      <div className="flex gap-2">
                        <Button size="small" icon={<Copy size={12} />} onClick={() => handleCopy(outputText)} className="!bg-white/5 !border-white/10 !text-white">Copy</Button>
                        <Button size="small" icon={<Download size={12} />} onClick={() => handleDownload(outputText, 'robots.txt')} className="!bg-white/5 !border-white/10 !text-white">Download</Button>
                      </div>
                    </div>
                    <TextArea 
                      rows={12}
                      value={outputText}
                      readOnly
                      placeholder="User-agent: *..."
                      className="!bg-white/[0.01] !border-white/10 !text-cyan-300 !rounded-xl font-mono text-xs"
                    />
                  </Col>
                </Row>
              </Card>
            )
          }
        ]}
      />

      <ToolContent toolKey="seo-suite" />
    </div>
  );
};

export default SeoSuite;
