export const ENGLISH = [
  'The Staff Selection Commission conducts exams for Lower Divisional Clerk posts. Candidates need thirty five words per minute speed.',
  'Railway Recruitment Board hires clerks and typists across India. Minimum speed required is twenty five words per minute.',
  'The Union Public Service Commission holds Civil Services Examination annually. It is one of the toughest exams in India.',
  'Banking sector jobs require candidates to qualify the Institute of Banking Personnel Selection examination. Typing speed matters.',
  'The High Court recruits Junior Clerks through competitive examinations. Candidates must type accurately in Hindi and English.',
  'CPCT is conducted by Madhya Pradesh government to certify computer proficiency. It tests Hindi and English typing speed.',
  'Government jobs in India are highly sought after due to job security and benefits. Lakhs of candidates appear each year.',
  'The National Recruitment Agency will conduct the Common Eligibility Test for Group B and C posts across India.',
  'SSC CHSL examination selects candidates for Data Entry Operators in various government offices and ministries of India.',
  'Postal Department recruits Postal Assistants through Staff Selection Commission exams. Typing speed of thirty five WPM needed.',
  'Income Tax Department recruits Tax Assistants through SSC CGL examination. Candidates must clear a typing skill test.',
  'The Central Secretariat Service recruits Section Officers through competitive examinations held by Union Public Service Commission.',
  'Rajasthan Public Service Commission conducts recruitment for various state government posts including clerk and typist positions.',
  'Uttar Pradesh Subordinate Services Selection Commission recruits stenographers and clerks for state government departments.',
  'The Food Corporation of India recruits Typist and Junior Engineers through direct recruitment and competitive examinations.',
  'Employees Provident Fund Organisation conducts exams for Social Security Assistants. Candidates need good typing and computer skills.',
  'Central Board of Direct Taxes recruits Income Tax Inspectors through Staff Selection Commission Combined Graduate Level exam.',
  'The Comptroller and Auditor General office recruits auditors and clerks through Staff Selection Commission examinations annually.',
  'Ministry of External Affairs recruits personal assistants and stenographers through competitive examinations held by government bodies.',
  'National Informatics Centre offers positions to computer professionals. Typing speed and accuracy are tested during recruitment.',
  'The Defence Research and Development Organisation recruits technical and administrative staff through various competitive examinations.',
  'Border Security Force recruits head constables and other posts through direct recruitment. Physical and written tests are held.',
  'Central Reserve Police Force conducts recruitment for constables and head constables. Good physical fitness is mandatory.',
  'Intelligence Bureau recruits security assistants and multi tasking staff through competitive written and typing examinations.',
  'The Serious Fraud Investigation Office requires trained typists and assistants for documentation and administrative work daily.',
  'Directorate General of Employment recruits Employment Officers through state public service commission examinations every year.',
  'National Bank for Agriculture and Rural Development recruits assistant managers through written examination and interview process.',
  'Small Industries Development Bank of India conducts exams for officer and assistant grade recruitment in various states.',
  'Reserve Bank of India recruits assistants and officers through competitive examinations. English typing test is compulsory.',
  'State Bank of India conducts probationary officer and clerk exams. Candidates must have basic computer and typing skills.',
  'Punjab National Bank holds recruitment drives for clerical posts. Typing test is part of the selection process.',
  'Canara Bank recruits clerks through the IBPS Common Recruitment Process. Computer knowledge and typing are tested.',
  'Allahabad High Court recruits Review Officers and Computer Operators through departmental and open competitive examinations.',
  'Madhya Pradesh High Court conducts exams for stenographers. Hindi typing speed of twenty five WPM is mandatory.',
  'Delhi Subordinate Services Selection Board recruits clerks and assistants for Delhi government departments through examinations.',
  'Haryana Staff Selection Commission conducts exams for Clerk Cum Data Entry Operator posts. Typing test is included.',
  'Bihar Public Service Commission holds exams for Assistant and Clerk positions in various state government departments.',
  'Tamil Nadu Public Service Commission recruits assistants through written exam followed by a typing proficiency test.',
  'Kerala Public Service Commission conducts recruitment for Lower Division Clerk posts in state government offices.',
  'Maharashtra Public Service Commission holds Rajyaseva examination for administrative positions in the Maharashtra state government.',
  'Andhra Pradesh Public Service Commission recruits assistants through group examinations. Telugu and English typing tested.',
  'Telangana State Public Service Commission conducts Group 4 exams for junior assistants in government departments.',
  'Gujarat Public Service Commission recruits administrative officers and clerks for state government departments via written tests.',
  'Rajasthan High Court conducts exams for personal assistants and stenographers. Shorthand and typing speeds are tested.',
  'Central Government Health Scheme recruits Lower Division Clerks and Data Entry Operators through Staff Selection Commission.',
  'National Health Mission recruits programme assistants at district level. Computer and typing proficiency is required.',
  'National Rural Health Mission hires data entry operators for health management information system data entry work.',
  'Integrated Child Development Services recruits supervisors and data entry operators at block and district levels.',
  'The Employees State Insurance Corporation recruits Upper Division Clerks and Stenos through competitive examinations.',
  'Oil and Natural Gas Corporation recruits administrative and technical staff. Written exam and skill test are conducted.',
]

export const HINDI = [
  'कर्मचारी चयन आयोग विभिन्न सरकारी विभागों में भर्ती के लिए परीक्षाएं आयोजित करता है। टाइपिंग गति आवश्यक है।',
  'रेलवे भर्ती बोर्ड देश भर में क्लर्क और टाइपिस्ट की भर्ती करता है। न्यूनतम गति पच्चीस शब्द प्रति मिनट है।',
  'उच्च न्यायालय जूनियर क्लर्क के पद के लिए प्रतियोगी परीक्षा आयोजित करता है। हिंदी टाइपिंग अनिवार्य है।',
  'कंप्यूटर प्रवीणता परीक्षण मध्यप्रदेश सरकार द्वारा आयोजित किया जाता है। हिंदी टाइपिंग गति की जांच होती है।',
  'भारत में सरकारी नौकरियां बहुत लोकप्रिय हैं। लाखों उम्मीदवार हर साल विभिन्न भर्ती परीक्षाओं में भाग लेते हैं।',
  'राष्ट्रीय भर्ती एजेंसी सामान्य पात्रता परीक्षा आयोजित करेगी। यह ग्रुप बी और सी पदों के लिए होगी।',
  'कर्मचारी भविष्य निधि संगठन सामाजिक सुरक्षा सहायकों की भर्ती करता है। कंप्यूटर और टाइपिंग कौशल आवश्यक है।',
  'आयकर विभाग स्टाफ सिलेक्शन कमीशन के माध्यम से टैक्स असिस्टेंट की भर्ती करता है। टाइपिंग परीक्षण होता है।',
  'भारतीय रिजर्व बैंक सहायक और अधिकारी पदों के लिए प्रतियोगी परीक्षाएं आयोजित करता है। अंग्रेजी टाइपिंग जरूरी है।',
  'भारतीय स्टेट बैंक में प्रोबेशनरी ऑफिसर और क्लर्क के लिए परीक्षा होती है। कंप्यूटर और टाइपिंग का ज्ञान आवश्यक है।',
  'मध्यप्रदेश उच्च न्यायालय स्टेनोग्राफर पदों के लिए परीक्षा आयोजित करता है। हिंदी टाइपिंग की गति अनिवार्य है।',
  'राजस्थान लोक सेवा आयोग विभिन्न राज्य सरकार के पदों के लिए भर्ती परीक्षाएं आयोजित करता है।',
  'उत्तर प्रदेश अधीनस्थ सेवा चयन आयोग स्टेनोग्राफर और क्लर्क की भर्ती करता है। टाइपिंग परीक्षण होता है।',
  'बिहार लोक सेवा आयोग सहायक और क्लर्क पदों के लिए विभिन्न राज्य सरकार विभागों में परीक्षाएं आयोजित करता है।',
  'हरियाणा कर्मचारी चयन आयोग क्लर्क सह डेटा एंट्री ऑपरेटर पदों के लिए परीक्षा आयोजित करता है।',
  'दिल्ली अधीनस्थ सेवा चयन बोर्ड दिल्ली सरकार के विभागों के लिए क्लर्क और सहायकों की भर्ती करता है।',
  'पंजाब नेशनल बैंक आईबीपीएस के माध्यम से क्लर्क की भर्ती करता है। टाइपिंग परीक्षण अनिवार्य होता है।',
  'इलाहाबाद उच्च न्यायालय समीक्षा अधिकारी और कंप्यूटर ऑपरेटर की भर्ती प्रतियोगी परीक्षाओं के माध्यम से करता है।',
  'केंद्र सरकार स्वास्थ्य योजना निचले प्रभाग के क्लर्क और डेटा एंट्री ऑपरेटर की भर्ती करती है।',
  'राष्ट्रीय स्वास्थ्य मिशन जिला स्तर पर डेटा एंट्री ऑपरेटर की भर्ती करता है। कंप्यूटर दक्षता आवश्यक है।',
  'खाद्य निगम ऑफ इंडिया टाइपिस्ट और जूनियर इंजीनियरों की भर्ती प्रत्यक्ष भर्ती और प्रतियोगी परीक्षाओं के माध्यम से करता है।',
  'कर्मचारी राज्य बीमा निगम अपर डिवीजन क्लर्क और स्टेनो की भर्ती प्रतियोगी परीक्षाओं के माध्यम से करता है।',
  'तेल और प्राकृतिक गैस निगम प्रशासनिक और तकनीकी कर्मचारियों की भर्ती करता है। लिखित परीक्षा और कौशल परीक्षण होते हैं।',
  'रक्षा अनुसंधान और विकास संगठन तकनीकी और प्रशासनिक कर्मचारियों की भर्ती विभिन्न प्रतियोगी परीक्षाओं के माध्यम से करता है।',
  'केंद्रीय रिजर्व पुलिस बल में कांस्टेबल और हेड कांस्टेबल की भर्ती होती है। शारीरिक फिटनेस अनिवार्य है।',
  'सीमा सुरक्षा बल हेड कांस्टेबल और अन्य पदों के लिए सीधी भर्ती करता है। शारीरिक और लिखित परीक्षण होती है।',
  'खुफिया ब्यूरो सुरक्षा सहायक और बहु-कार्य कर्मचारियों की भर्ती प्रतियोगी परीक्षाओं के माध्यम से करता है।',
  'नाबार्ड सहायक प्रबंधकों की भर्ती लिखित परीक्षा और साक्षात्कार प्रक्रिया के माध्यम से करता है।',
  'भारतीय लघु उद्योग विकास बैंक विभिन्न राज्यों में अधिकारी और सहायक ग्रेड की भर्ती के लिए परीक्षाएं आयोजित करता है।',
  'डाक विभाग स्टाफ सिलेक्शन कमीशन परीक्षाओं के माध्यम से डाक सहायकों की भर्ती करता है। पैंतीस डब्ल्यूपीएम चाहिए।',
  'महाराष्ट्र लोक सेवा आयोग महाराष्ट्र राज्य सरकार में प्रशासनिक पदों के लिए राज्यसेवा परीक्षा आयोजित करता है।',
  'गुजरात लोक सेवा आयोग लिखित परीक्षाओं के माध्यम से राज्य सरकार के विभागों के लिए प्रशासनिक अधिकारियों की भर्ती करता है।',
  'तमिलनाडु लोक सेवा आयोग लिखित परीक्षा के बाद टाइपिंग दक्षता परीक्षण के माध्यम से सहायकों की भर्ती करता है।',
  'केरल लोक सेवा आयोग राज्य सरकार के कार्यालयों में लोअर डिवीजन क्लर्क पदों के लिए भर्ती आयोजित करता है।',
  'आंध्र प्रदेश लोक सेवा आयोग समूह परीक्षाओं के माध्यम से सहायकों की भर्ती करता है। तेलुगु और अंग्रेजी टाइपिंग की जांच होती है।',
  'तेलंगाना राज्य लोक सेवा आयोग सरकारी विभागों में जूनियर सहायकों के लिए ग्रुप चार परीक्षाएं आयोजित करता है।',
  'एकीकृत बाल विकास सेवाएं ब्लॉक और जिला स्तरों पर सुपरवाइजर और डेटा एंट्री ऑपरेटरों की भर्ती करती है।',
  'संघ लोक सेवा आयोग सिविल सेवा परीक्षा हर साल आयोजित करता है। यह भारत की सबसे कठिन परीक्षाओं में से एक है।',
  'बैंकिंग क्षेत्र में नौकरियों के लिए आईबीपीएस परीक्षा योग्य करना आवश्यक है। टाइपिंग गति महत्वपूर्ण भूमिका निभाती है।',
  'राजस्थान उच्च न्यायालय व्यक्तिगत सहायकों और स्टेनोग्राफरों के लिए परीक्षा आयोजित करता है। शॉर्टहैंड और टाइपिंग गति की जांच होती है।',
  'केंद्रीय प्रत्यक्ष कर बोर्ड स्टाफ सिलेक्शन कमीशन सीजीएल परीक्षा के माध्यम से आयकर निरीक्षकों की भर्ती करता है।',
  'महालेखा परीक्षक और नियंत्रक कार्यालय स्टाफ सिलेक्शन कमीशन परीक्षाओं के माध्यम से लेखा परीक्षकों और क्लर्कों की भर्ती करता है।',
  'विदेश मंत्रालय प्रतियोगी परीक्षाओं के माध्यम से व्यक्तिगत सहायक और स्टेनोग्राफर की भर्ती करता है।',
  'राष्ट्रीय सूचना विज्ञान केंद्र कंप्यूटर पेशेवरों के लिए पद प्रदान करता है। टाइपिंग गति और सटीकता परखी जाती है।',
  'भारतीय रेलवे दुनिया का सबसे बड़ा नियोक्ता है और देश भर में भर्ती परीक्षाएं आयोजित करती है।',
  'क्लर्क या टाइपिस्ट पद के लिए हिंदी में न्यूनतम तीस शब्द प्रति मिनट की टाइपिंग गति आवश्यक है।',
  'सामान्य ज्ञान और गणित के प्रश्न सभी सरकारी परीक्षाओं में पूछे जाते हैं। अच्छी तैयारी सफलता की कुंजी है।',
  'टाइपिंग अभ्यास नियमित रूप से करें। प्रतिदिन कम से कम एक घंटे का अभ्यास आपकी गति और सटीकता बढ़ाएगा।',
  'हिंदी टाइपिंग के लिए कृतिदेव और मंगल फॉन्ट का उपयोग किया जाता है। दोनों का अभ्यास आवश्यक है।',
  'सरकारी परीक्षाओं की तैयारी के लिए नियमित अध्ययन और टाइपिंग अभ्यास दोनों आवश्यक हैं। समय का सदुपयोग करें।',
]
